export interface BrazilState {
  code: string;
  name: string;
  /** Top 10 cities by population, capital always first (used as the default). */
  cities: string[];
}

// Population-ranked shortlists, not an exhaustive municipality list — good
// enough for a "pick your city" dropdown without needing to load/search
// through the 5000+ municipalities in Brazil.
export const BRAZIL_STATES: BrazilState[] = [
  {
    code: "AC",
    name: "Acre",
    cities: [
      "Rio Branco",
      "Cruzeiro do Sul",
      "Sena Madureira",
      "Tarauacá",
      "Feijó",
      "Brasiléia",
      "Senador Guiomard",
      "Xapuri",
      "Plácido de Castro",
      "Epitaciolândia",
    ],
  },
  {
    code: "AL",
    name: "Alagoas",
    cities: [
      "Maceió",
      "Arapiraca",
      "Palmeira dos Índios",
      "Rio Largo",
      "Penedo",
      "União dos Palmares",
      "São Miguel dos Campos",
      "Delmiro Gouveia",
      "Coruripe",
      "Santana do Ipanema",
    ],
  },
  {
    code: "AP",
    name: "Amapá",
    cities: [
      "Macapá",
      "Santana",
      "Laranjal do Jari",
      "Oiapoque",
      "Mazagão",
      "Porto Grande",
      "Tartarugalzinho",
      "Vitória do Jari",
      "Ferreira Gomes",
      "Pedra Branca do Amapari",
    ],
  },
  {
    code: "AM",
    name: "Amazonas",
    cities: [
      "Manaus",
      "Parintins",
      "Itacoatiara",
      "Manacapuru",
      "Coari",
      "Tefé",
      "Tabatinga",
      "Maués",
      "Humaitá",
      "Iranduba",
    ],
  },
  {
    code: "BA",
    name: "Bahia",
    cities: [
      "Salvador",
      "Feira de Santana",
      "Vitória da Conquista",
      "Camaçari",
      "Itabuna",
      "Juazeiro",
      "Lauro de Freitas",
      "Ilhéus",
      "Jequié",
      "Teixeira de Freitas",
    ],
  },
  {
    code: "CE",
    name: "Ceará",
    cities: [
      "Fortaleza",
      "Caucaia",
      "Juazeiro do Norte",
      "Maracanaú",
      "Sobral",
      "Crato",
      "Itapipoca",
      "Maranguape",
      "Iguatu",
      "Quixadá",
    ],
  },
  {
    code: "DF",
    name: "Distrito Federal",
    cities: [
      "Brasília",
      "Ceilândia",
      "Taguatinga",
      "Samambaia",
      "Planaltina",
      "Águas Claras",
      "Recanto das Emas",
      "Gama",
      "Guará",
      "Santa Maria",
    ],
  },
  {
    code: "ES",
    name: "Espírito Santo",
    cities: [
      "Vitória",
      "Vila Velha",
      "Serra",
      "Cariacica",
      "Linhares",
      "Cachoeiro de Itapemirim",
      "São Mateus",
      "Colatina",
      "Guarapari",
      "Aracruz",
    ],
  },
  {
    code: "GO",
    name: "Goiás",
    cities: [
      "Goiânia",
      "Aparecida de Goiânia",
      "Anápolis",
      "Rio Verde",
      "Luziânia",
      "Águas Lindas de Goiás",
      "Valparaíso de Goiás",
      "Trindade",
      "Formosa",
      "Novo Gama",
    ],
  },
  {
    code: "MA",
    name: "Maranhão",
    cities: [
      "São Luís",
      "Imperatriz",
      "São José de Ribamar",
      "Timon",
      "Caxias",
      "Codó",
      "Paço do Lumiar",
      "Açailândia",
      "Bacabal",
      "Balsas",
    ],
  },
  {
    code: "MT",
    name: "Mato Grosso",
    cities: [
      "Cuiabá",
      "Várzea Grande",
      "Rondonópolis",
      "Sinop",
      "Tangará da Serra",
      "Cáceres",
      "Sorriso",
      "Lucas do Rio Verde",
      "Primavera do Leste",
      "Barra do Garças",
    ],
  },
  {
    code: "MS",
    name: "Mato Grosso do Sul",
    cities: [
      "Campo Grande",
      "Dourados",
      "Três Lagoas",
      "Corumbá",
      "Ponta Porã",
      "Naviraí",
      "Nova Andradina",
      "Aquidauana",
      "Sidrolândia",
      "Maracaju",
    ],
  },
  {
    code: "MG",
    name: "Minas Gerais",
    cities: [
      "Belo Horizonte",
      "Uberlândia",
      "Contagem",
      "Juiz de Fora",
      "Betim",
      "Montes Claros",
      "Ribeirão das Neves",
      "Uberaba",
      "Governador Valadares",
      "Ipatinga",
    ],
  },
  {
    code: "PA",
    name: "Pará",
    cities: [
      "Belém",
      "Ananindeua",
      "Santarém",
      "Marabá",
      "Parauapebas",
      "Castanhal",
      "Abaetetuba",
      "Cametá",
      "Marituba",
      "Bragança",
    ],
  },
  {
    code: "PB",
    name: "Paraíba",
    cities: [
      "João Pessoa",
      "Campina Grande",
      "Santa Rita",
      "Patos",
      "Bayeux",
      "Sousa",
      "Cabedelo",
      "Cajazeiras",
      "Guarabira",
      "Sapé",
    ],
  },
  {
    code: "PR",
    name: "Paraná",
    cities: [
      "Curitiba",
      "Londrina",
      "Maringá",
      "Ponta Grossa",
      "Cascavel",
      "São José dos Pinhais",
      "Foz do Iguaçu",
      "Colombo",
      "Guarapuava",
      "Paranaguá",
    ],
  },
  {
    code: "PE",
    name: "Pernambuco",
    cities: [
      "Recife",
      "Jaboatão dos Guararapes",
      "Olinda",
      "Caruaru",
      "Petrolina",
      "Paulista",
      "Cabo de Santo Agostinho",
      "Camaragibe",
      "Garanhuns",
      "Vitória de Santo Antão",
    ],
  },
  {
    code: "PI",
    name: "Piauí",
    cities: [
      "Teresina",
      "Parnaíba",
      "Picos",
      "Piripiri",
      "Floriano",
      "Campo Maior",
      "Barras",
      "União",
      "Altos",
      "Esperantina",
    ],
  },
  {
    code: "RJ",
    name: "Rio de Janeiro",
    cities: [
      "Rio de Janeiro",
      "São Gonçalo",
      "Duque de Caxias",
      "Nova Iguaçu",
      "Niterói",
      "Belford Roxo",
      "Campos dos Goytacazes",
      "São João de Meriti",
      "Petrópolis",
      "Volta Redonda",
    ],
  },
  {
    code: "RN",
    name: "Rio Grande do Norte",
    cities: [
      "Natal",
      "Mossoró",
      "Parnamirim",
      "São Gonçalo do Amarante",
      "Macaíba",
      "Ceará-Mirim",
      "Caicó",
      "Assu",
      "Currais Novos",
      "Santa Cruz",
    ],
  },
  {
    code: "RS",
    name: "Rio Grande do Sul",
    cities: [
      "Porto Alegre",
      "Caxias do Sul",
      "Pelotas",
      "Canoas",
      "Santa Maria",
      "Gravataí",
      "Viamão",
      "Novo Hamburgo",
      "São Leopoldo",
      "Rio Grande",
    ],
  },
  {
    code: "RO",
    name: "Rondônia",
    cities: [
      "Porto Velho",
      "Ji-Paraná",
      "Ariquemes",
      "Vilhena",
      "Cacoal",
      "Rolim de Moura",
      "Guajará-Mirim",
      "Jaru",
      "Ouro Preto do Oeste",
      "Buritis",
    ],
  },
  {
    code: "RR",
    name: "Roraima",
    cities: [
      "Boa Vista",
      "Rorainópolis",
      "Caracaraí",
      "Alto Alegre",
      "Mucajaí",
      "Cantá",
      "Bonfim",
      "Normandia",
      "São João da Baliza",
      "São Luiz",
    ],
  },
  {
    code: "SC",
    name: "Santa Catarina",
    cities: [
      "Florianópolis",
      "Joinville",
      "Blumenau",
      "São José",
      "Chapecó",
      "Itajaí",
      "Criciúma",
      "Jaraguá do Sul",
      "Palhoça",
      "Balneário Camboriú",
    ],
  },
  {
    code: "SP",
    name: "São Paulo",
    cities: [
      "São Paulo",
      "Guarulhos",
      "Campinas",
      "São Bernardo do Campo",
      "Santo André",
      "Osasco",
      "São José dos Campos",
      "Ribeirão Preto",
      "Sorocaba",
      "Mauá",
    ],
  },
  {
    code: "SE",
    name: "Sergipe",
    cities: [
      "Aracaju",
      "Nossa Senhora do Socorro",
      "Lagarto",
      "Itabaiana",
      "São Cristóvão",
      "Estância",
      "Tobias Barreto",
      "Simão Dias",
      "Nossa Senhora da Glória",
      "Propriá",
    ],
  },
  {
    code: "TO",
    name: "Tocantins",
    cities: [
      "Palmas",
      "Araguaína",
      "Gurupi",
      "Porto Nacional",
      "Paraíso do Tocantins",
      "Colinas do Tocantins",
      "Guaraí",
      "Tocantinópolis",
      "Miracema do Tocantins",
      "Dianópolis",
    ],
  },
];

export function getCitiesForState(code: string): string[] {
  return BRAZIL_STATES.find((s) => s.code === code)?.cities ?? [];
}

export function getCapitalForState(code: string): string | undefined {
  return getCitiesForState(code)[0];
}
